# Generated by Django 5.0.4 on 2026-05-20 09:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Print3DMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ABS', 'ABS'), ('PLA', 'PLA'), ('PETG', 'PETG')], default='ABS', max_length=5, verbose_name='متریال')),
                ('color', models.CharField(max_length=12, verbose_name='رنگ')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting', 'در انتظار تایید'), ('processing', 'در حال پردازش'), ('sent', 'ارسال شده'), ('delivered', 'تحویل شده'), ('canceled', 'لغو شده'), ('returned', 'مرجوع شده')], default='waiting', max_length=10)),
                ('delivery_type', models.CharField(choices=[('post', 'پست معمولی'), ('pishtaz', 'پست پیشتاز')], default='post', max_length=10)),
                ('delivery_price', models.IntegerField(blank=True, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=24, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='print_3D.order')),
            ],
        ),
        migrations.CreateModel(
            name='Print3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='print3D/', verbose_name='فایل')),
                ('infill', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تراکم')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stl_images/')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print3d', to='print_3D.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print3d', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='print_3D.print3dmaterial', verbose_name='متریال')),
            ],
            options={
                'verbose_name': 'print3D',
                'verbose_name_plural': 'print3Ds',
            },
        ),
    ]
