# Generated by Django 5.0.4 on 2026-05-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='print3d',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='print3d',
            name='file',
            field=models.FileField(upload_to='uploads/print3D/', verbose_name='فایل'),
        ),
    ]
