# Generated by Django 5.0.4 on 2026-05-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0002_print3d_description_alter_print3d_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='print3d',
            old_name='quantity',
            new_name='qty',
        ),
    ]
