# Generated by Django 5.0.4 on 2026-05-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0003_rename_quantity_print3d_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('pending_payment', 'در انتظار پرداخت'), ('pending_receipt', 'در انتظار تایید '), ('preparing', 'در پروسه تولید'), ('shipping', 'در حال ارسال'), ('completed', 'پایان یافته')], default='pending', max_length=20),
        ),
    ]
