# Generated by Django 5.0.4 on 2026-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0004_remove_order_status_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='print3d',
            name='state',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('pending_payment', 'در انتظار پرداخت'), ('pending_receipt', 'در انتظار تایید '), ('preparing', 'در پروسه تولید'), ('shipping', 'در حال ارسال'), ('completed', 'پایان یافته')], default='pending', max_length=20),
        ),
    ]
