# Generated by Django 5.0.4 on 2026-05-20 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_company'),
        ('print_3D', '0005_print3d_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print3d',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print3d', to='accounts.profile'),
        ),
    ]
