# Generated by Django 5.0.4 on 2026-05-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0006_alter_print3d_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='print3d',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='uploads/receipts/'),
        ),
    ]
