# Generated by Django 5.0.4 on 2026-05-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0007_print3d_payment_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print3d',
            name='material',
        ),
        migrations.AddField(
            model_name='print3d',
            name='color',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='print3d',
            name='type',
            field=models.CharField(blank=True, choices=[('ABS', 'ABS'), ('PLA', 'PLA'), ('PETG', 'PETG')], default='ABS', max_length=5, null=True, verbose_name='متریال'),
        ),
        migrations.AlterField(
            model_name='print3d',
            name='infill',
            field=models.CharField(blank=True, choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=3, null=True, verbose_name='تراکم'),
        ),
    ]
