# Generated by Django 5.0.4 on 2026-05-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0008_remove_print3d_material_print3d_color_print3d_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print3d',
            name='type',
        ),
        migrations.AddField(
            model_name='print3d',
            name='material',
            field=models.CharField(blank=True, choices=[('ABS', 'ABS'), ('PLA', 'PLA'), ('PETG', 'PETG')], default='ABS', max_length=5, null=True, verbose_name='متریال'),
        ),
    ]
