# Generated by Django 5.0.4 on 2026-05-23 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0009_remove_print3d_type_print3d_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print3d',
            name='color',
        ),
        migrations.AlterField(
            model_name='print3d',
            name='infill',
            field=models.CharField(blank=True, choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default='10', max_length=3, null=True, verbose_name='تراکم'),
        ),
        migrations.AlterField(
            model_name='print3d',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print3d', to='print_3D.print3dmaterial'),
        ),
    ]
