# Generated by Django 5.0.4 on 2026-05-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0010_remove_print3d_color_alter_print3d_infill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='print3d',
            name='color',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='print3d',
            name='material',
            field=models.CharField(blank=True, choices=[('ABS', 'ABS'), ('PLA', 'PLA'), ('PETG', 'PETG')], default='ABS', max_length=5, null=True, verbose_name='متریال'),
        ),
    ]
