# Generated by Django 5.0.4 on 2026-05-23 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0011_print3d_color_alter_print3d_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print3d',
            name='color',
        ),
        migrations.AlterField(
            model_name='print3d',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print3d', to='print_3D.print3dmaterial'),
        ),
    ]
