# Generated by Django 5.0.4 on 2026-05-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0012_remove_print3d_color_alter_print3d_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='print3dmaterial',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
