# Generated by Django 5.0.4 on 2026-05-23 12:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0013_print3dmaterial_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='print3dmaterial',
            name='color_hex',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='رنگ'),
        ),
    ]
