# Generated by Django 5.0.4 on 2026-06-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0014_print3dmaterial_color_hex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='print3dmaterial',
            options={'ordering': ['-is_available', 'display_order', 'id'], 'verbose_name': 'متریال چاپ سه\u200cبعدی', 'verbose_name_plural': 'متریال\u200cهای چاپ سه\u200cبعدی'},
        ),
        migrations.AddField(
            model_name='print3dmaterial',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
