# Generated by Django 5.0.4 on 2026-06-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_3D', '0015_alter_print3dmaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='print3dmaterial',
            options={'ordering': ['-is_available', '-display_order', 'id'], 'verbose_name': 'متریال چاپ سه\u200cبعدی', 'verbose_name_plural': 'متریال\u200cهای چاپ سه\u200cبعدی'},
        ),
        migrations.AddField(
            model_name='print3dmaterial',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت هر کیلوگرم'),
        ),
    ]
