# Generated by Django 5.0.4 on 2026-05-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_material', models.CharField(choices=[('FR_4', 'FR-4'), ('Flex', 'Flex'), ('Aluminum', 'Aluminum'), ('Copper_Core', 'Copper Core'), ('Rogers', 'Rogers'), ('PTFE_Teflon', 'PTFE Teflon')], default='FR_4', max_length=20)),
                ('layers', models.IntegerField()),
                ('substrate_type', models.CharField(choices=[('mm', 'میلی متر'), ('inch', 'اینچ')], default='25µm', max_length=20)),
                ('dimension_x', models.IntegerField()),
                ('dimension_y', models.IntegerField()),
                ('dimension_unit', models.CharField(choices=[('mm', 'میلی متر'), ('inch', 'اینچ')], default='mm', max_length=20)),
                ('qty', models.CharField(choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('50', '50'), ('75', '75'), ('100', '100'), ('125', '125'), ('150', '150'), ('200', '200'), ('250', '250'), ('300', '300'), ('350', '350'), ('400', '400'), ('450', '450'), ('500', '500'), ('600', '600'), ('700', '700'), ('750', '750'), ('800', '800'), ('900', '900'), ('1000', '1000'), ('1200', '1200'), ('1250', '1250'), ('1400', '1400'), ('1500', '1500'), ('1600', '1600'), ('1750', '1750'), ('1800', '1800'), ('2000', '2000'), ('2400', '2400'), ('2500', '2500'), ('2800', '2800'), ('3000', '3000'), ('3500', '3500'), ('4000', '4000'), ('4500', '4500'), ('5000', '5000'), ('5500', '5500'), ('6000', '6000'), ('6500', '6500'), ('7000', '7000'), ('7500', '7500'), ('8000', '8000'), ('8500', '8500'), ('9000', '9000'), ('9500', '9500'), ('10000', '10000'), ('11000', '11000'), ('12000', '12000'), ('13000', '13000'), ('14000', '14000'), ('15000', '15000'), ('16000', '16000'), ('17000', '17000'), ('18000', '18000'), ('19000', '19000'), ('25000', '25000'), ('30000', '30000'), ('40000', '40000'), ('50000', '50000'), ('60000', '60000'), ('70000', '70000')], default='5', max_length=20)),
                ('product_type', models.CharField(choices=[('FR_4', 'FR-4'), ('Flex', 'Flex'), ('Aluminum', 'Aluminum'), ('Copper_Core', 'Copper Core'), ('Rogers', 'Rogers'), ('PTFE_Teflon', 'PTFE Teflon')], default='Industrial', max_length=20)),
                ('panel', models.BooleanField()),
                ('PCB_thickness', models.CharField(choices=[('0.4mm', '0.4mm'), ('0.6mm', '0.6mm'), ('0.8mm', '0.8mm'), ('1.0mm', '1.0mm'), ('1.2mm', '1.2mm'), ('1.6mm', '1.6mm'), ('2.0mm', '2.0mm')], default='0.4mm', max_length=20)),
                ('PCB_color', models.CharField(choices=[('green', 'سبز'), ('purple', 'بنفش'), ('red', 'قرمز'), ('yellow', 'زرد'), ('blue', 'آبی'), ('white', 'سفید'), ('black', 'سیاه')], default='green', max_length=20)),
                ('silkscreen', models.CharField(choices=[('green', 'سبز'), ('purple', 'بنفش'), ('red', 'قرمز'), ('yellow', 'زرد'), ('blue', 'آبی'), ('white', 'سفید'), ('black', 'سیاه')], default='white', max_length=20)),
                ('material_type', models.CharField(choices=[('FR4_TG135', 'FR4 TG135'), ('Nan_Ya_NP_140F', 'Nan Ya NP-140F'), ('KB6164_TG135', 'KB6164 - TG135'), ('S1000H_TG155', 'S1000H TG155'), ('S1141_TG140', 'S1141 TG140'), ('Electro_deposited', 'Electro-deposited'), ('Rolled_Annealed', 'Rolled Annealed'), ('RO4350B', 'RO4350B(Dk=3.48, Df=0.0037)'), ('ZYF300CA-P', 'ZYF300CA-P(Dk=3.0, Df=0.0018)'), ('ZYF300CA-C', 'ZYF300CA-C(Dk=2.94, Df=0.0016)'), ('ZYF265D', 'ZYF265D(Dk=2.65, Df=0.0019)'), ('ZYF255DA', 'ZYF255DA(Dk=2.55, Df=0.0018')], default='white', max_length=20)),
                ('surface_finish', models.CharField(choices=[('HASL', 'HASL(with lead)'), ('LeadFree_HASL', 'LeadFree HASL'), ('ENIG', 'ENIG'), ('OSP', 'OSP')], default='white', max_length=20)),
                ('gold_thickness', models.CharField(choices=[('1U', '1 U"'), ('2U', '2 U"')], default='white', max_length=20)),
                ('outer_copper_weight', models.CharField(choices=[('1', '1 oz'), ('2', '2 oz'), ('2.5', '2.5 oz'), ('3.5', '3.5 oz'), ('4.5', '4.5 oz')], default='white', max_length=20)),
                ('via_covering', models.CharField(choices=[('Tented', 'Tented'), ('UnTented', 'UnTented'), ('Plugged', 'Plugged'), ('Epoxy', 'Epoxy Filled & Capped'), ('Copper', 'Copper paste Filled & Capped')], default='white', max_length=20)),
                ('min_via', models.CharField(choices=[('0.3mm', '0.3mm/(0.4/0.45mm)'), ('0.25mm', '0.3mm/(0.35/0.4mm)'), ('0.2mm', '0.3mm/(0.3/0.35mm)'), ('0.315mm', '0.3mm/(0.25/0.3mm)')], default='white', max_length=20)),
                ('board_outline_tolerance', models.CharField(choices=[('0.2mm', '±0.2mm(Regular)'), ('0.1mm', '±0.1mm(Precision)')], default='white', max_length=20)),
                ('electrical_test', models.CharField(choices=[('Random_Test', 'Flying Probe Random Test'), ('Fully_Test', 'Flying Probe Fully Test'), ('E_Test', 'E-Test Fixture')], default='white', max_length=20)),
            ],
        ),
    ]
