# Generated by Django 5.0.4 on 2026-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='material_type',
        ),
        migrations.AlterField(
            model_name='board',
            name='PCB_thickness',
            field=models.CharField(choices=[('0.4', '0.4mm'), ('0.6', '0.6mm'), ('0.8', '0.8mm'), ('1.0', '1.0mm'), ('1.2', '1.2mm'), ('1.6', '1.6mm'), ('2.0', '2.0mm')], default='0.4', max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='base_material',
            field=models.CharField(choices=[('fr4', 'FR-4'), ('flex', 'Flex'), ('aluminum', 'Aluminum'), ('copper', 'Copper Core'), ('rogers', 'Rogers'), ('ptfe', 'PTFE Teflon')], default='FR_4', max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_outline_tolerance',
            field=models.CharField(choices=[('0.2', '±0.2mm(Regular)'), ('0.1', '±0.1mm(Precision)')], default='0.2', max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='electrical_test',
            field=models.CharField(choices=[('random', 'Flying Probe Random Test'), ('fully', 'Flying Probe Fully Test'), ('e', 'E-Test Fixture')], default='random', max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='gold_thickness',
            field=models.CharField(choices=[('1U', '1 U"'), ('2U', '2 U"')], default='1U', max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='min_via',
            field=models.CharField(choices=[('0.3', '0.3mm/(0.4/0.45mm)'), ('0.25', '0.3mm/(0.35/0.4mm)'), ('0.2', '0.3mm/(0.3/0.35mm)'), ('0.315', '0.3mm/(0.25/0.3mm)')], default='0.3', max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='outer_copper_weight',
            field=models.CharField(choices=[('1', '1 oz'), ('2', '2 oz'), ('2.5', '2.5 oz'), ('3.5', '3.5 oz'), ('4.5', '4.5 oz')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='product_type',
            field=models.CharField(choices=[('industrial', 'صنعتی مصرفی'), ('aerospace', 'هوا فضا'), ('medical', 'پزشکی')], default='industrial', max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='substrate_type',
            field=models.CharField(blank=True, choices=[('25µm', 'ضخامت دی\u200cالکتریک  ۲۵µm'), ('50µm', 'ضخامت دی\u200cالکتریک ۵۰µm'), ('transparent', ' شفاف')], default='25µm', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='surface_finish',
            field=models.CharField(choices=[('HASL', 'HASL(with lead)'), ('LeadFree_HASL', 'LeadFree HASL'), ('ENIG', 'ENIG'), ('OSP', 'OSP')], default='HASL', max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='via_covering',
            field=models.CharField(choices=[('Tented', 'Tented'), ('UnTented', 'UnTented'), ('Plugged', 'Plugged'), ('Epoxy', 'Epoxy Filled & Capped'), ('Copper', 'Copper paste Filled & Capped')], default='Tented', max_length=20),
        ),
    ]
