# Generated by Django 5.0.4 on 2026-05-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_board', '0002_remove_board_material_type_alter_board_pcb_thickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
