# Generated by Django 5.0.4 on 2026-05-12 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
        ('pcb_board', '0004_alter_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات پروژه'),
        ),
        migrations.AddField(
            model_name='board',
            name='grid_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='grid_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='state',
            field=models.CharField(choices=[('pending', 'در دست بررسی'), ('preparing', 'در پروسه تولید'), ('shipping', 'در حال ارسال'), ('completed', 'پایان یافته')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.profile'),
        ),
    ]
