# Generated by Django 5.0.4 on 2026-05-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_board', '0005_board_created_at_board_description_board_grid_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='electrical_test',
            field=models.CharField(choices=[('random', 'رندوم'), ('fully', 'تست کامل')], default='random', max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='product_type',
            field=models.CharField(choices=[('industrial', 'صنعتی / مصرفی'), ('aerospace', 'هوا فضا'), ('medical', 'پزشکی')], default='industrial', max_length=20),
        ),
    ]
