# Generated by Django 5.0.4 on 2026-05-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_board', '0006_alter_board_electrical_test_alter_board_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='board',
            name='state',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('preparing', 'در پروسه تولید'), ('shipping', 'در حال ارسال'), ('completed', 'پایان یافته')], default='pending', max_length=20),
        ),
    ]
