# Generated by Django 5.0.4 on 2026-05-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_board', '0007_board_cost_alter_board_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
