# Generated by Django 5.0.4 on 2026-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_board', '0009_alter_board_description_alter_board_grid_x_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='cost',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='board',
            name='base_material',
            field=models.CharField(choices=[('fr4', 'FR-4'), ('flex', 'Flex'), ('aluminum', 'Aluminum'), ('copper', 'Copper Core'), ('rogers', 'Rogers'), ('ptfe', 'PTFE Teflon')], default='FR_4', max_length=20, verbose_name='نوع برد '),
        ),
        migrations.AlterField(
            model_name='board',
            name='layers',
            field=models.IntegerField(verbose_name='تعداد لایه\u200cها'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام برد'),
        ),
        migrations.AlterField(
            model_name='board',
            name='state',
            field=models.CharField(blank=True, choices=[('pending', 'در حال بررسی'), ('pending_payment', 'در انتظار پرداخت'), ('preparing', 'در پروسه تولید'), ('shipping', 'در حال ارسال'), ('completed', 'پایان یافته')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='board',
            name='substrate_type',
            field=models.CharField(blank=True, choices=[('25µm', 'ضخامت دی\u200cالکتریک  ۲۵µm'), ('50µm', 'ضخامت دی\u200cالکتریک ۵۰µm'), ('transparent', ' شفاف')], default='25µm', max_length=20, null=True, verbose_name='نوع بستر '),
        ),
    ]
