# Generated by Django 5.0.4 on 2026-05-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_board', '0010_rename_cost_board_price_alter_board_base_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='PCB_color',
            field=models.CharField(choices=[('green', 'سبز'), ('purple', 'بنفش'), ('red', 'قرمز'), ('yellow', 'زرد'), ('blue', 'آبی'), ('white', 'سفید'), ('black', 'سیاه')], default='green', max_length=20, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='board',
            name='PCB_thickness',
            field=models.CharField(choices=[('0.4', '0.4mm'), ('0.6', '0.6mm'), ('0.8', '0.8mm'), ('1.0', '1.0mm'), ('1.2', '1.2mm'), ('1.6', '1.6mm'), ('2.0', '2.0mm')], default='0.4', max_length=20, verbose_name='ضخامت'),
        ),
        migrations.AlterField(
            model_name='board',
            name='board_outline_tolerance',
            field=models.CharField(choices=[('0.2', '±0.2mm(Regular)'), ('0.1', '±0.1mm(Precision)')], default='0.2', max_length=20, verbose_name='تلرانس ابعاد برد'),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='board',
            name='electrical_test',
            field=models.CharField(choices=[('random', 'رندوم'), ('fully', 'تست کامل')], default='random', max_length=20, verbose_name='تست الکتریکال'),
        ),
        migrations.AlterField(
            model_name='board',
            name='gold_thickness',
            field=models.CharField(choices=[('1U', '1 U"'), ('2U', '2 U"')], default='1U', max_length=20, verbose_name='ضخامت طلا '),
        ),
        migrations.AlterField(
            model_name='board',
            name='min_via',
            field=models.CharField(choices=[('0.3', '0.3mm/(0.4/0.45mm)'), ('0.25', '0.3mm/(0.35/0.4mm)'), ('0.2', '0.3mm/(0.3/0.35mm)'), ('0.315', '0.3mm/(0.25/0.3mm)')], default='0.3', max_length=20, verbose_name='حداقل قطر ویا'),
        ),
        migrations.AlterField(
            model_name='board',
            name='outer_copper_weight',
            field=models.CharField(choices=[('1', '1 oz'), ('2', '2 oz'), ('2.5', '2.5 oz'), ('3.5', '3.5 oz'), ('4.5', '4.5 oz')], default='1', max_length=20, verbose_name='ضخامت مس'),
        ),
        migrations.AlterField(
            model_name='board',
            name='panel',
            field=models.BooleanField(verbose_name='پنل شده'),
        ),
        migrations.AlterField(
            model_name='board',
            name='product_type',
            field=models.CharField(choices=[('industrial', 'صنعتی / مصرفی'), ('aerospace', 'هوا فضا'), ('medical', 'پزشکی')], default='industrial', max_length=20, verbose_name='کاربرد'),
        ),
        migrations.AlterField(
            model_name='board',
            name='qty',
            field=models.CharField(choices=[('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('50', '50'), ('75', '75'), ('100', '100'), ('125', '125'), ('150', '150'), ('200', '200'), ('250', '250'), ('300', '300'), ('350', '350'), ('400', '400'), ('450', '450'), ('500', '500'), ('600', '600'), ('700', '700'), ('750', '750'), ('800', '800'), ('900', '900'), ('1000', '1000'), ('1200', '1200'), ('1250', '1250'), ('1400', '1400'), ('1500', '1500'), ('1600', '1600'), ('1750', '1750'), ('1800', '1800'), ('2000', '2000'), ('2400', '2400'), ('2500', '2500'), ('2800', '2800'), ('3000', '3000'), ('3500', '3500'), ('4000', '4000'), ('4500', '4500'), ('5000', '5000'), ('5500', '5500'), ('6000', '6000'), ('6500', '6500'), ('7000', '7000'), ('7500', '7500'), ('8000', '8000'), ('8500', '8500'), ('9000', '9000'), ('9500', '9500'), ('10000', '10000'), ('11000', '11000'), ('12000', '12000'), ('13000', '13000'), ('14000', '14000'), ('15000', '15000'), ('16000', '16000'), ('17000', '17000'), ('18000', '18000'), ('19000', '19000'), ('25000', '25000'), ('30000', '30000'), ('40000', '40000'), ('50000', '50000'), ('60000', '60000'), ('70000', '70000')], default='5', max_length=20, verbose_name='تعداد برد'),
        ),
        migrations.AlterField(
            model_name='board',
            name='silkscreen',
            field=models.CharField(choices=[('green', 'سبز'), ('purple', 'بنفش'), ('red', 'قرمز'), ('yellow', 'زرد'), ('blue', 'آبی'), ('white', 'سفید'), ('black', 'سیاه')], default='white', max_length=20, verbose_name='رنگ چاپ'),
        ),
        migrations.AlterField(
            model_name='board',
            name='surface_finish',
            field=models.CharField(choices=[('HASL', 'HASL(with lead)'), ('LeadFree_HASL', 'LeadFree HASL'), ('ENIG', 'ENIG'), ('OSP', 'OSP')], default='HASL', max_length=20, verbose_name='پوشش نهایی'),
        ),
        migrations.AlterField(
            model_name='board',
            name='via_covering',
            field=models.CharField(choices=[('Tented', 'Tented'), ('UnTented', 'UnTented'), ('Plugged', 'Plugged'), ('Epoxy', 'Epoxy Filled & Capped'), ('Copper', 'Copper paste Filled & Capped')], default='Tented', max_length=20, verbose_name='پوشش ویا'),
        ),
    ]
