# Generated by Django 5.0.4 on 2026-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_board', '0011_board_payment_receipt_alter_board_pcb_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pcb_file/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='uploads/receipts/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='state',
            field=models.CharField(blank=True, choices=[('pending', 'در حال بررسی'), ('pending_payment', 'در انتظار پرداخت'), ('pending_receipt', 'در انتظار تایید '), ('preparing', 'در پروسه تولید'), ('shipping', 'در حال ارسال'), ('completed', 'پایان یافته')], default='pending', max_length=30),
        ),
    ]
