# Generated by Django 5.0.4 on 2026-05-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_board', '0012_board_file_alter_board_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='file_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
