# Generated by Django 5.0.4 on 2026-05-04 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('id_code', models.CharField(max_length=11)),
                ('company', models.CharField(max_length=11)),
                ('postal_code', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'staff'), ('customer', 'Customer')], default='user', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
