# Generated by Django 5.0.4 on 2026-05-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commercial_code',
            field=models.CharField(max_length=11, null=True, verbose_name='کداقتصادی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(max_length=11, verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_code',
            field=models.CharField(max_length=11, verbose_name='کدملی / شناسه\u200cملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(max_length=11, verbose_name='کدپستی'),
        ),
    ]
