# Generated by Django 5.0.4 on 2026-05-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_commercial_code_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='commercial_code',
            field=models.CharField(max_length=11, verbose_name='کداقتصادی'),
        ),
    ]
