# Generated by Django 5.0.4 on 2026-05-12 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='commercial_code',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='کداقتصادی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_code',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='کدملی / شناسه\u200cملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
