# Generated by Django 5.0.4 on 2026-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_commercial_code_alter_profile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شرکت'),
        ),
    ]
